FROM golang:1.15

WORKDIR /app

COPY ./src /app/src
COPY ./runner.conf /app/runner.conf

RUN go get github.com/gorilla/mux \
  gopkg.in/go-playground/validator.v9 \
  github.com/satori/go.uuid \
  github.com/stretchr/testify \
  github.com/pilu/fresh

CMD [ "fresh" ]
