FROM golang:1.15

WORKDIR /app

COPY ./src /app/src

RUN go get github.com/gorilla/mux \
  gopkg.in/go-playground/validator.v9 \
  github.com/jinzhu/gorm \
  github.com/jinzhu/gorm/dialects/sqlite \
  github.com/satori/go.uuid \
  github.com/stretchr/testify
