version: "3"

services:
  api:
    container_name: mapi-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./runner.conf:/app/runner.conf
      - ./dlv.sh:/app/dlv.sh
    ports:
      - 8080:8080
      - 6868:6868
    env_file:
      - ./.env
    environment:
      PORT: $PORT
    restart: always
